# Port du serveur
server.port=8080

# R2DBC PostgreSQL
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/usersdb
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# Activer le SQL pour le debug
spring.r2dbc.show-sql=true